# Generated by Django 2.2.3 on 2022-02-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220206_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='content_de',
        ),
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=models.TextField(blank=True),
        ),
    ]
